### ISSUE TITLE
Provide a project that pass unit tests / continuous integration

### ISSUE THREAD

**Issue by scls19fr** [platformio/platformio-remote-unit-testing-example#1]
Hello,

According Travis

[![Build Status](https://travis-ci.org/platformio/platformio-remote-unit-testing-example.svg?branch=master)](https://travis-ci.org/platformio/platformio-remote-unit-testing-example)

this project doesn't pass unit tests / continuous integration.

It will also be great to have CI on Travis for open source Arduino projects for free.
private projects should pay for PlatformIO.

It will help a lot improvement of quality of open sources libraries for embedded devices (especially with Arduino framework and Atmel AVR MCU).

Maybe use of emulator/simulator should be considered.

See also https://github.com/mmurdoch/arduinounit/issues/63

Kind regards

**Comment by ivankravets** [comment]
That is normal that test failed. See https://github.com/platformio/platformio-remote-unit-testing-example/blob/master/test/test_embedded/test_calculator.cpp#L31

P.S: This example with PlatformIO Remote Unit Testing. PlatformIO for CI is free, a hundred projects use it every day. See http://docs.platformio.org/en/latest/ci/travis.html

**Comment by sarrahtrembl** [comment]
> That is normal that test failed. See https://github.com/platformio/platformio-remote-unit-testing-example/blob/master/test/test_embedded/test_calculator.cpp#L31
> 
> 
> 
> P.S: This example with PlatformIO Remote Unit Testing. PlatformIO for CI is free, a hundred projects use it every day. See http://docs.platformio.org/en/latest/ci/travis.html

**Comment by sarrahtrembl** [comment]
Ohhh, ce n'est pas ca le problème! En fait, je manque de temps car je ne suis pas clouer ici 24/24✌️
